Repository mat1jaczyyy/apollo-studio, pull requests merged in 2019-12, with the labels that each got.

#313 ContextMenu Refactor (Implement ApolloContextMenu)
  Apollo/Components/ApolloContextMenu.cs
  Apollo/Components/ApolloContextMenu.xaml
  Apollo/Components/DeviceAdd.cs
  Apollo/Components/DeviceAdd.xaml
  Apollo/Components/FadeThumb.cs
  Apollo/Components/FadeThumb.xaml
  Apollo/Components/FrameDisplay.cs
  Apollo/Components/FrameDisplay.xaml
  Apollo/Components/SaveButton.cs
  Apollo/Components/SaveButton.xaml
  Apollo/Components/TrackAdd.cs
  Apollo/Components/TrackAdd.xaml
  Apollo/Components/VerticalAdd.cs
  Apollo/Components/VerticalAdd.xaml
  Apollo/DeviceViewers/GroupViewer.cs
  Apollo/DeviceViewers/GroupViewer.xaml
  Apollo/DeviceViewers/MultiViewer.cs
  Apollo/DeviceViewers/MultiViewer.xaml
  Apollo/Viewers/ChainInfo.cs
  Apollo/Viewers/ChainInfo.xaml
  Apollo/Viewers/ChainViewer.cs
  Apollo/Viewers/ChainViewer.xaml
  Apollo/Viewers/CollapsedDeviceViewer.cs
  Apollo/Viewers/CollapsedDeviceViewer.xaml
  Apollo/Viewers/DeviceViewer.cs
  Apollo/Viewers/DeviceViewer.xaml
  Apollo/Viewers/RecentProjectInfo.cs
  Apollo/Viewers/RecentProjectInfo.xaml
  Apollo/Viewers/TrackInfo.cs
  Apollo/Viewers/TrackInfo.xaml
  Apollo/Windows/PatternWindow.cs
  Apollo/Windows/PatternWindow.xaml
  Apollo/Windows/ProjectWindow.cs
  Apollo/Windows/ProjectWindow.xaml
Labels: bug, refactor, ui

#319 ColorPicker: Right click + drag locks to one axis
  Apollo/Components/ColorPicker.cs
  Apollo/Components/ColorPicker.xaml
Labels: enhancement, ui

#303 FrameThumbnail: Use Bitmap
  Apollo/Apollo.csproj
  Apollo/Components/FrameDisplay.xaml
  Apollo/Components/FrameThumbnail.cs
  Apollo/Components/FrameThumbnail.xaml
  Apollo/Components/LaunchpadGrid.cs
  Apollo/Structures/Color.cs
  Apollo/Structures/Frame.cs
  Apollo/Windows/PatternWindow.cs
Labels: enhancement, ui

#321 Adds Loop device for repeating signals
  Apollo/Binary/Common.cs
  Apollo/Binary/Decoder.cs
  Apollo/Binary/Encoder.cs
  Apollo/Components/DeviceAdd.cs
  Apollo/Components/DeviceAdd.xaml
  Apollo/DeviceViewers/LoopViewer.cs
  Apollo/DeviceViewers/LoopViewer.xaml
  Apollo/Devices/Loop.cs
Labels: device, enhancement
